Repository golang/dep, pull requests merged in 2018-07, with the labels that each got.

#1872 gps: unset some GIT_* variables for git operations
  gps/cmd.go
Labels: cla: yes

#1860 Makefile: use simple variables
  Makefile
Labels: cla: yes

#1866 gps: prevent hg extensions from interfering
  gps/vcs_source.go
Labels: cla: yes

#1781 Support additional details with status command
  Makefile
  cmd/dep/status.go
  cmd/dep/status_test.go
  hack/test.bash
Labels: cla: no

#1884 gps: Remove versionTypeUnion
  cmd/dep/testdata/harness_tests/ensure/add/desync/final/Gopkg.lock
  cmd/dep/testdata/harness_tests/ensure/empty/case2/final/Gopkg.lock
  cmd/dep/testdata/harness_tests/ensure/pkg-ignored/wildcard-ignore/final/Gopkg.lock
  cmd/dep/testdata/harness_tests/ensure/update/case1/final/Gopkg.lock
  cmd/dep/testdata/harness_tests/ensure/update/desync/final/Gopkg.lock
  cmd/dep/testdata/harness_tests/init/gvt/case1/initial/vendor/manifest
  gps/constraint.go
  gps/constraint_test.go
  gps/satisfy.go
  gps/selection.go
  gps/solve_basic_test.go
  gps/solver.go
  gps/version.go
  gps/version_unifier.go
  gps/version_unifier_test.go
Labels: area: gps, cla: yes

#1911 Adding more emphasis to the need of create a go file before running ensure
  docs/new-project.md
Labels: cla: yes

#1868 test: unset GIT_DIR for git operations in integration tests
  internal/test/integration/testproj.go
Labels: cla: yes

#1921 Don't exclude Godeps folder. Fixes #1822
  CHANGELOG.md
  gps/pkgtree/pkgtree.go
Labels: cla: yes

#1889 Add the git+ssh rewrite config settings
  docs/FAQ.md
Labels: cla: yes

#1925 main.go: fix printing of 'dep -h'
  cmd/dep/main.go
Labels: cla: yes

#1941 Removes "echo" statement introduced with commit 918c75
  install.sh
Labels: cla: yes

#1942 remove extra "directly" word and extra comma
  docs/ensure-mechanics.md
Labels: cla: yes

#1588 graphviz: project-package relationship graph
  CHANGELOG.md
  cmd/dep/graphviz.go
  cmd/dep/graphviz_test.go
  cmd/dep/status.go
  cmd/dep/testdata/graphviz/case1.dot
  cmd/dep/testdata/graphviz/case2.dot
  cmd/dep/testdata/graphviz/empty.dot
  cmd/dep/testdata/graphviz/subgraph1.dot
  cmd/dep/testdata/graphviz/subgraph2.dot
  cmd/dep/testdata/graphviz/subgraph3.dot
  cmd/dep/testdata/graphviz/subgraph4.dot
Labels: area: status, cla: yes

#1939 Document DEPCACHEAGE in env-vars.md
  docs/env-vars.md
Labels: cla: yes

#1948 Improve handling of paths containing repeated separators (fix #1946).
  context.go
  context_test.go
  internal/fs/fs.go
  internal/fs/fs_test.go
Labels: cla: yes

#1950 Add wikipedia link for CDCL in documentation
  docs/the-solver.md
Labels: cla: yes

#1951 status: Accommodate new verify systems
  cmd/dep/status.go
  cmd/dep/status_test.go
Labels: cla: yes

#1954 add documentation explaining how to uninstall
  docs/installation.md
  docs/uninstalling.md
  website/sidebars.json
Labels: cla: yes
