Repository golang/dep, pull requests merged in 2018-02, with the labels that each got.

#1671 Document how to install dep from source
  docs/installation.md
Labels: cla: yes

#1672 Refer to new docs instead of GitHub in `Gopkg.toml` example
  testdata/txn_writer/expected_manifest.toml
  txn_writer.go
Labels: cla: yes

#1673 [FIX] Cleanup code
  cmd/dep/ensure_test.go
  cmd/dep/gopath_scanner_test.go
  cmd/dep/prune.go
  cmd/dep/status.go
  cmd/dep/status_test.go
  gps/deduce.go
  gps/filesystem_test.go
  gps/solve_basic_test.go
  gps/solve_bimodal_test.go
  hack/licenseok/main.go
  internal/importers/base/importer.go
  internal/test/integration/testproj.go
  internal/test/test.go
  manifest.go
  manifest_test.go
Labels: cla: yes

#1664 Added lost documentation about generating graph visualizations
  docs/daily-dep.md
Labels: cla: yes

#1594 docs: Document website local setup
  CONTRIBUTING.md
  website/package.json
Labels: cla: yes

#1676 Make it easier for contributors to mimic a PR
  .travis.yml
  Makefile
Labels: cla: yes

#1675 Lock Docusaurus npm packages
  website/package-lock.json
Labels: cla: yes

#1677 Added two lost docs Testing changes to a dependency, Changing dependencies
  docs/FAQ.md
Labels: cla: yes

#1640 godep: Import additional packages as required
  internal/importers/godep/importer.go
  internal/importers/godep/importer_test.go
  internal/importers/importertest/testcase.go
Labels: cla: yes

#1620 increment CI go versions from 1.8.x/1.9.x/tip to 1.9.x/1.10.x/tip
  .travis.yml
  CHANGELOG.md
  appveyor.yml
Labels: cla: yes

#1607 Website styles
  website/.gitignore
  website/siteConfig.js
  website/static/css/custom.css
Labels: cla: yes

#1533 Install.sh script for dep
  CHANGELOG.md
  README.md
  install.sh
Labels: cla: yes

#1650 Update docs to reflect default prune settings
  docs/Gopkg.toml.md
Labels: cla: yes

#1646 gps: BenchmarkCreateVendorTree - fatal error instead of nil panic
  gps/solution_test.go
Labels: cla: yes

#1618 Use tagged releases and canonical import paths
  Gopkg.lock
  Gopkg.toml
  internal/importers/glide/importer.go
  internal/importers/govend/importer.go
  vendor/github.com/go-yaml/yaml/LICENSE
  vendor/github.com/golang/protobuf/proto/discard.go
  vendor/github.com/pelletier/go-toml/keysparsing.go
  vendor/github.com/pelletier/go-toml/lexer.go
  vendor/github.com/pelletier/go-toml/marshal.go
  vendor/github.com/pelletier/go-toml/parser.go
  vendor/github.com/pelletier/go-toml/token.go
  vendor/github.com/pelletier/go-toml/toml.go
  vendor/github.com/pelletier/go-toml/tomltree_write.go
  vendor/gopkg.in/yaml.v2/LICENSE
  vendor/gopkg.in/yaml.v2/LICENSE.libyaml
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/emitterc.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/parserc.go
  vendor/gopkg.in/yaml.v2/readerc.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/sorter.go
  vendor/gopkg.in/yaml.v2/writerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/gopkg.in/yaml.v2/yamlprivateh.go
Labels: cla: yes

#1475 Note diffs b/w imported and solved lock
  cmd/dep/root_analyzer.go
  internal/feedback/feedback.go
  internal/feedback/feedback_test.go
Labels: cla: no

#1708 change CI to 1.10.x; update docs
  .travis.yml
  README.md
Labels: cla: yes

#1250 gps: fine grained source transitions
  CHANGELOG.md
  gps/deduce.go
  gps/deduce_test.go
  gps/error.go
  gps/manager_test.go
  gps/maybe_source.go
  gps/maybe_source_test.go
  gps/pkgtree/pkgtree.go
  gps/pkgtree/pkgtree_test.go
  gps/source.go
  gps/source_cache.go
  gps/source_cache_bolt.go
  gps/source_cache_bolt_encode.go
  gps/source_cache_bolt_test.go
  gps/source_cache_multi.go
  gps/source_cache_test.go
  gps/source_manager.go
  gps/source_test.go
  gps/vcs_repo.go
  gps/vcs_repo_test.go
  gps/vcs_source.go
  gps/vcs_source_test.go
Labels: area: gps, cla: yes

#1707 typo: Fix method name in comment
  gps/manifest.go
Labels: cla: yes

#1697 modify daily-dep grammar and sentence structure
  docs/daily-dep.md
Labels: cla: yes, docs

#1473 Add profiling flags
  cmd/dep/main.go
Labels: cla: yes
