Repository golang/dep, pull requests merged in 2018-03, with the labels that each got.

#1730 fix install script when curl is not available
  install.sh
Labels: cla: yes

#1549 Dep status -f doc and string display
  cmd/dep/status.go
  cmd/dep/status_test.go
Labels: area: status, cla: yes

#1732 Update Changelog for #1549 and typo fixes
  CHANGELOG.md
  cmd/dep/status.go
Labels: cla: yes

#1710 Clarified which manifest fields apply only to the root project in docs.
  docs/Gopkg.toml.md
  website/yarn.lock
Labels: cla: yes

#1755 Added file extension to windows install
  install.sh
Labels: cla: yes

#1751 Fix typos and optimize images
  docs/FAQ.md
  docs/Gopkg.lock.md
  docs/Gopkg.toml.md
  docs/assets/DigbyFlat.png
  docs/assets/DigbyFlat.svg
  docs/assets/DigbyFlatScene2.png
  docs/assets/DigbyFlatScene2.svg
  docs/assets/DigbyScene2Flat.png
  docs/assets/DigbyScene2Flat.svg
  docs/assets/DigbyScene2Shadows.png
  docs/assets/DigbyScene2Shadows.svg
  docs/assets/DigbyShadows.png
  docs/assets/DigbyShadows.svg
  docs/assets/DigbyShadowsScene2.png
  docs/assets/DigbyShadowsScene2.svg
  docs/assets/StatusGraph.png
  docs/assets/annotated-func-arrows.png
  docs/assets/base-arrows.png
  docs/assets/four-states.png
  docs/assets/func-toggles.png
  docs/assets/in-sync.png
  docs/assets/lock-back.png
  docs/assets/required-arrows.png
  docs/daily-dep.md
  docs/deduction.md
  docs/ensure-mechanics.md
  docs/failure-modes.md
  docs/glossary.md
  docs/installation.md
  docs/introduction.md
  docs/migrating.md
  docs/new-project.md
  docs/the-solver.md
  gps/pkgtree/digest_test.go
  gps/prune.go
  gps/prune_test.go
Labels: cla: yes

#1770 Fix hyperlink for CoC in contribution guide
  CONTRIBUTING.md
Labels: cla: yes

#1743 Fix issue 1742 by replacing '>' with '>='
  gps/pkgtree/pkgtree.go
Labels: cla: yes

#1699 Docs search
  .travis.yml
  website/siteConfig.js
Labels: cla: yes, docs
